export const actionConstants = {
    TOGGLE_MENU : 'TOGGLE_MENU',
    CLOSE_MENU : 'CLOSE_MENU',
    GET_DANGERZONES: 'GET_DANGERZONES',
    POST_DANGERZONE: 'POST_DANGERZONE',
    RECEIVED_DANGERZONES : 'RECEIVED_DANGERZONES',
    DELETED_DANGERZONE : 'DELETED_DANGERZONE',
    ADD_DANGERZONE: 'ADD_DANGERZONE',
    RECEIVED_NODES : 'RECEIVED_NODES',
    STORE_UPLINKMESSAGES: 'STORE_UPLINKMESSAGES',
    STORE_GATEWAYS: 'STORE_GATEWAYS',
}